###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mysql:
      image: mysql:5.7.22
      container_name: ecom-mysql
      working_dir: /application
      volumes:
        - .:/application
        - './.data/mysql:/var/lib/mysql'
      restart: always
      command: '--default-authentication-plugin=mysql_native_password'
      environment:
        - MYSQL_ROOT_PASSWORD=root@123
        - MYSQL_DATABASE=db_app
        - MYSQL_USER=user_app
        - MYSQL_PASSWORD=pass_app
      ports:
        - "3333:3306"

    webserver:
      image: nginx:alpine
      container_name: ecom-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8181:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ecom-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ~/.ssh:/root/.ssh
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    # redis
    cache:
      image: redis:3.0-alpine
    adminer:
      image: adminer
      restart: always
      ports:
        - 8282:8080
      links:
        - mysql:db

